[package]
name = "briefly-searcher-telegram"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
briefly-searcher-storage.workspace = true
grammers-client.workspace = true
grammers-session.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
sqlx.workspace = true
