[package]
name = "briefly-searcher"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
briefly-searcher-storage.workspace = true
briefly-searcher-telegram.workspace = true
anyhow.workspace = true
askama.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
dotenvy.workspace = true
envconfig.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http-body-util.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tower.workspace = true
